# Torch를 사용한 Tensor 만들기

In [21]:
import torch
import numpy as np

In [11]:
def describe(x):
    print(f"타입 : {x.type()}")
    print(f"크기 : {x.shape}")
    print(f"값 : \n{x}")
    print("\n")

In [12]:
describe(torch.Tensor(2, 3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[0.0000e+00, 7.9874e-44, 6.4896e-10],
        [8.3025e-10, 2.7447e-06, 6.6766e-07]])




In [13]:
describe(torch.rand(2, 3)) # 균등 분포

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[0.1111, 0.6543, 0.4092],
        [0.4420, 0.3589, 0.4524]])




In [14]:
describe(torch.randn(2, 3)) # 정규 분포

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[-0.2119, -0.2601, -0.1345],
        [-2.0077, -0.2518,  0.1913]])




In [19]:
describe(torch.zeros(2,3))
describe(torch.ones(2,3))
x = torch.zeros(2,3)
x.fill_(5)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[5., 5., 5.],
        [5., 5., 5.]])




In [20]:
x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])




In [22]:
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

타입 : torch.DoubleTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[0.6281, 0.3268, 0.9050],
        [0.6769, 0.6597, 0.9725]], dtype=torch.float64)




# Tensor 타입과 크기

In [23]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])




In [24]:
x = x.long()
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[1, 2, 3],
        [4, 5, 6]])




In [25]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int64)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[1, 2, 3],
        [4, 5, 6]])




In [27]:
x = x.float()
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[1., 2., 3.],
        [4., 5., 6.]])




# Tensor 연산

In [28]:
x = torch.randn(2,3)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값 : 
tensor([[-0.6622,  0.2510, -0.4818],
        [ 0.8495, -1.8206,  0.4098]])


